version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - django-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  django-app:
    build: .
    container_name: django-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - django-network
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...' &&
        while ! nc -z mysql-db 3306; do
          sleep 1
        done &&
        echo 'MySQL is ready!' &&
        python manage.py migrate --no-input &&
        python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8000 --workers 3 myproject.wsgi:application
      "

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - django-app
    networks:
      - django-network

volumes:
  mysql-data:
  static_volume:
  media_volume:

networks:
  django-network: