apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: jaishankar7655/django-app:latest   # <== apna push kiya hua image lagana
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secret
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: django-app
spec:
  selector:
    app: django
  ports:
  - port: 8000
    targetPort: 8000
  clusterIP: None
