apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: library-app-hpa
  namespace: library-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: library-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
