apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: django-app
type: Opaque
data:
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQta2V5LWNvbXBsZXRlbHktaGlkZQ==   # base64
  DB_PASSWORD: YXBwcGFzcw==   # base64 of "apppass"
