apiVersion: v1
kind: Service
metadata:
  name: library-app-service
  namespace: library-app
spec:
  selector:
    app: library-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP   # बाहर expose करना हो तो LoadBalancer कर सकते हो
